server:
  port: 8443
  ssl:
    key-store: classpath:certificates/springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
    enabled: true

spring:
  liquibase:
    change-log: classpath:/db/changelog-master.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/LibraryManagement
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mika
