server:
  port: 8443

spring:
  liquibase:
    change-log: classpath:/db/changelog-master.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/LibraryManagement
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mika
